USERS_LIST = "/users/"
LOGIN_BY_PASSWORD = "/token/"
REFRESH_TOKEN = "/token/refresh/"
USER_PRIVATE_DATA = "/users/me"
MESSAGES = "/chats/{chat_id}/messages/"
CHATS = "/chats/"
CHAT_USERS = CHATS + "{chat_id}/users/"
